name: Build FTC Robot Controller
on:
  push:
    branches: [ "main", "master" ]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'
      - name: Create debug keystore
        run: |
          mkdir -p libs
          keytool -genkey -v -keystore libs/ftc.debug.keystore -alias androiddebugkey -keyalg RSA -keysize 2048 -validity 10000 -storepass android -keypass android -dname "CN=Android Debug,O=Android,C=US"
      - name: Build with Gradle
        run: gradle assembleRelease
      - name: Upload APK
        uses: actions/upload-artifact@v4
        with:
          name: robot-controller-apk
          path: FtcRobotController/build/outputs/apk/release/FtcRobotController-release.apk